export const EDIT_POPUP_CLOSE = "EDIT_POPUP_CLOSE";
export const EDIT_POPUP_OPEN = "EDIT_POPUP_OPEN";

export const CHANGEPWD_POPUP_CLOSE = "CHANGEPWD_POPUP_CLOSE";
export const CHANGEPWD_POPUP_OPEN = "CHANGEPWD_POPUP_OPEN";

export const FORGOT_PWD_POPUP_CLOSE = "FORGOT_PWD_POPUP_CLOSE";
export const FORGOT_PWD_POPUP_OPEN = "FORGOT_PWD_POPUP_OPEN";